function opts=opts_default()
opts.plot           = 0;
opts.verbose        = 0;
opts.parametertype  = 'Y';
opts.method         ='sdp';
opts.poletype       ='lincmplx';
opts.tol            = 0;
opts.enforceDC      = 0;
opts.wgt_scheme     = 3;
